# -*- coding: utf-8 -*-
"""SLPBanglaCharacter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12lf8aTB9HVXZc5lq63fXRiGo6T0QgaIL
"""

import numpy as np
import pandas as pd

from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.optimizers import Adam, SGD, RMSprop
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split

bornoDict =	{
  'অ': 1,
  'আ': 2,
  'ই': 3,
  'ঈ': 4,
  'উ': 5,
  'ঊ': 6,
  'ঋ': 7,
  'এ': 8,
  'ঐ': 9,
  'ও': 10,
  'ঔ': 11,
  'ক': 12,
  'খ': 13,
  'গ': 14,
  'ঘ': 15,
  'ঙ': 16,
  'চ': 17,
  'ছ': 18,
  'জ': 19,
  'ঝ': 20,
  'ঞ': 21,
  'ট': 22,
  'ঠ': 23,
  'ড': 24,
  'ঢ': 25,
  'ণ': 26,
  'ত': 27,
  'থ': 28,
  'দ': 29,
  'ধ': 30,
  'ন': 31,
  'প': 32,
  'ফ': 33,
  'ব': 34,
  'ভ': 35,
  'ম': 36,
  'য': 37,
  'র': 38,
  'ল': 39,
  'শ': 40,
  'ষ': 41,
  'স': 42,
  'হ': 43,
  'ড়': 44,
  'ঢ়': 45,
  'য়': 46
}

def wordCharacterToUnicode(arr, arrOutput):
  for i in range(0, len(arr)):
    temp = arr[i];
    count = 0
    for j in temp:
      arrOutput[i][count]= ord(j) - 2400
      count = count + 1

def labelCharacterToInteger(arry, arryoutput):
  for i in range (0, len(arry)):
        arryoutput[i]= bornoDict[arry[i]]


data = pd.read_csv('inputbn.csv', sep=',', engine='python', header=0)
data = data.to_numpy()

x_sample = data[:,0]
y_sample = data[:,1]

X = np.zeros(shape = (100, 10))
wordCharacterToUnicode(x_sample, X)
Y = np.zeros(shape = (100, 1))
labelCharacterToInteger(y_sample, Y)
print(X[0:5])
print(Y[0:5])

trainX, testX, trainy, testy = train_test_split(X, Y, test_size=0.2)

opt = Adam(lr = 0.001)
model = Sequential()
model.add(Dense(output_dim=1, init='uniform', activation='relu', input_dim=10))
model.compile(optimizer=opt, loss='mean_squared_error', metrics=['accuracy'])
history = model.fit(trainX, trainy, validation_data=(testX, testy), batch_size=2, epochs=1000, verbose=2)
model.summary()

# evaluate the keras model
loss, accuracy = model.evaluate(X, Y)
print("\nLoss: %.3f, Accuracy: %.2f%%" % (loss, accuracy*100))

history_dict = history.history
history_dict.keys()

import matplotlib.pyplot as plt

acc = history_dict['acc']
loss = history_dict['loss']
epochs = range(1, len(loss) + 1)

# "bo" is for "blue dot"
plt.plot(epochs, loss, 'bo', label='Training loss')
plt.title('Training loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.show()

plt.clf()   # clear figure

plt.plot(epochs, acc, color='darkblue', label='Training acc' )
plt.title('Training accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend(loc='lower right')

plt.show()

tempString = 'সরকারি'
Y = bornoDict['স']
tempInput = np.zeros(shape=(1,10))
count = 0
for i in tempString:
  tempInput[0][count]= ord(i) - 2400
  count = count + 1
print(tempInput)
probability = model.predict(tempInput)
print(probability)

key_list = list(bornoDict.keys()) 
val_list = list(bornoDict.values()) 
probability = np.round(probability)
print(probability)  
print(key_list[val_list.index(probability)])